### PR TITLE
Routing support for ES JOIN data type.

### PR DESCRIPTION
**Pull request by mashhur**
Hi guys~

At least please give me comments where I did wrong and for what cases it fails.
I really need this feature and could not wait for [routing issue](https://issues.couchbase.com/browse/DOC-4478). So, here I tried to implement.
If you really consider this way is OK, 
 - *how to articulate travel-sample (airlines & airports) as a parent-child relationship* has to be added to toml example.
 - how to unit testing

Thanks!

### CODE REVIEW

**Comment by hartmut-co-uk** [comment]
ref: https://twitter.com/hartmut_co_uk/status/1078243503338078209

**Comment by hartmut-co-uk** [comment]
I think it should be more abstract in the way to avoid using the term `parent` and stick with `routing` - as the ES `_routing` field is simply used to resolve on which particular shard the document is assigned to. So it's not necessarily used for relations to other indexes (parent-child).

**Comment by hartmut-co-uk** [comment]
> One of the problems with supporting routing based on a document field is that it makes it difficult to delete the document, since the document body is not available to the connector during deletion.

uh, thanks for pointing out! This is a problem indeed 😞.
I guess to provide routing support - with the implication to not support deletes is at least something.

> Is it acceptable for specifying a routing to also imply ignoreDeletes=true?

IMO I think I'd rather fail during the startup phase & throw an error if routing is configured, but not `ignoreDeletes=true`.

**Comment by mashhur** [comment]
Thank you very much @hartmut-co-uk  and @dnault !
Appreciate you feedbacks!

 -- I agree with @hartmut-co-uk that it would be good to call the config property routing instead of parent.
 --> Initially I had also same idea to use only routing. After carefully reading ES join documentation inside the *JOIN type field* ES defines *parent* field. From this point of view, this feature users can confuse. However, if you guys vote for change, it is not a huge deal. I will refactor! Giving my point!

-- A good improvement would be to specify the routing field using a JSON pointer. That would allow it to be nested anywhere in the document. This could be made to work with documentContentAtTopLevel = false by modifying the routing pointer to look under the 'doc' node.
  --> So far (demo) only top level supported, I can easily add this too. Let me add it!

-- One of the problems with supporting routing based on a document field is that it makes it difficult to delete the document, since the document body is not available to the connector during deletion. For example, if you try to delete one of the "child" documents, I would expect you'll get an entry in the rejection log.
  --> This is little conservative that if ES mapping required routing you have a point otherwise it seems it is not connector's job! Let me test on both cases, research on lil bit and come back.

Questions for everyone:
  -- Is support for custom routing all that's required in order to use parent/join fields?
    --> Didn't get this question, could you please explain little more? Is it from ES side?
  -- Is it acceptable for specifying a routing to also imply ignoreDeletes=true?
    --> *# If true, never delete matching documents from Elasticsearch.* Is there any other process except toml explanation? I couldn't catch routing-ignoreDeletes relation (it seems for me different process).

Thank you!

**Comment by dnault** [comment]
>Is support for custom routing all that's required in order to use parent/join fields?
>> Didn't get this question, could you please explain little more? Is it from ES side?

I don't see any changes in this PR that are specific to parent/join; I only saw changes for specifying a custom routing. Once we add routing, do we need to add anything else to make parent/join fields work?

> Is it acceptable for specifying a routing to also imply ignoreDeletes=true?
>> \# If true, never delete matching documents from Elasticsearch. Is there any other process except toml explanation? I couldn't catch routing-ignoreDeletes relation (it seems for me different process).

Routing based on field means deletion will fail. Do you think the connector should automatically ignore deletes when routing is used?

**Comment by dnault** [comment]
>  @dnault: Is it acceptable for specifying a routing to also imply ignoreDeletes=true?
>> @hartmut-co-uk: I think I'd rather fail during the startup phase & throw an error if routing is configured, but not ignoreDeletes=true.

That's a nice idea, makes it obvious to the user what will happen.

**Comment by hartmut-co-uk** [comment]
my understanding is - deletion will fail for most documents - as when `_routing` isn't used for the DELETE - ES will use the `_id` to hash -> calculate the shard - and send+process the DELETE on that particular ES node::shard only - which would therefore only success for a subset of documents where the hash for `_id` matches the custom hash for `_rouring`... so DELETEs can't be supported.
Is there no way on Couchbase side to get the entity body on DELETE event?

**Comment by mashhur** [comment]
> > Is support for custom routing all that's required in order to use parent/join fields?
> > > Didn't get this question, could you please explain little more? Is it from ES side?
> 
> I don't see any changes in this PR that are specific to parent/join; I only saw changes for specifying a custom routing. Once we add routing, do we need to add anything else to make parent/join fields work?
> 
> > Is it acceptable for specifying a routing to also imply ignoreDeletes=true?
> > > If true, never delete matching documents from Elasticsearch. Is there any other process except toml explanation? I couldn't catch routing-ignoreDeletes relation (it seems for me different process).
> 
> Routing based on field means deletion will fail. Is this okay?

In case of **ignoreDeletes=true** only check point(s) update is required (ElasticSearchWriter.java -> 167 line). No any request going to ES. So, I thinks it is a normal case, no need to do any action with routing.

**Comment by mashhur** [comment]
So, @hartmut-co-uk and @dnault ,
I guess I went wrong way! To be honest with you guys, I didn't know custom routing is different from parent-child routing though. I mean I needed routing for parent-child and considered only this process. Since **custom routing and parent-child routing** are different (learnt routing :)), I had to point out parent-child routing rather than pointing  [routing issue](https://issues.couchbase.com/browse/CBES-106).

So, @dnault if couchbase planned to support parent-child relationship (like parentSelector in old versions), you can consider this PR. Otherwise better I close it.
Thank you!

**Comment by hartmut-co-uk** [comment]
@mashhur 
I think the way parent-child works certainly is something specific - BUT my understanding of the documentation is - that you need to ensure / use the regular ES `_routing` for the children to ensure they're on the same shard as the parent document.
This is either 
- by using the parent ID as custom _routing_ value for the children (as that same parent `_id` is used by default for the parent document for the routing hash)
- or by using a same custom routing both for the parent & child documents

So I think in addition to specifying the specific 'parent-child' fields - you as well require to use the 'custom routing' for the child documents (with the simplest way being to use the parent `_id` as the custom routing to match the parent's default routing).

That would result in the same issue / limitation that deletes won't work for child documents - as the entity body would be required to resolve the routing value.

See ES documentation reference:
> screenshot 2019-01-07 at 11 55 24

**Comment by mashhur** [comment]
@hartmut-co-uk 
I am agree with you on **parent-child works certainly is something specific** and your post is mainly about indexing. However, our discussion(different points) came on DELETE action.
Here I have drawn a diagram which illustrates difference of **custom routing vs parent-child routing** on actions.

screen shot 2019-01-08 at 10 56 39 am


Here is the screenshot from ES doc page, which saying for the custom routing we cannot use join. So, from this point of view IMHO parent-child has to be seen alone (not together with custom routing). 
screen shot 2019-01-08 at 10 47 20 am

Another controversy is the [documentation urges](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html), on every action routing value is required. So, I [posted this question](https://discuss.elastic.co/t/parent-child-deletion-documentation-says-routing-is-required-but-without-routing-it-works-es-6-5v/163290?u=mashhur) on ES forum & contacted to ES dev support team. Once I get clear answer, I will share it here too.

**Comment by mashhur** [comment]
@hartmut-co-uk, @dnault  

I have now clear view that custom routing and routing of parent-child are same!
Why my document was deleted is I had only one index with shard :( (since it is DEV)

Here, I got clear explanation and experiment why without routing child deletion will not work.
https://discuss.elastic.co/t/parent-child-deletion-documentation-says-routing-is-required-but-without-routing-it-works-es-6-5v/163290
 
So, now the question is:
 1) @dnault, Can couchbase send document body (at least routing value) in case of delete event?
 2) In case of 1 option impossible, how do you guys think if I FETCH the doc first and then delete the doc using fetched routing value?

Thank you!

**Comment by mashhur** [comment]
@dnault , thank you for feedbacks.
As you pointed It seems the best way of achieving custom routing is to attach to document ID. How do you think if we simply **_add routing field to .toml as it clearly points to_** (in order to not to confuse)?
Both additional field and regex are ok, simple and clear way would be perfect.
 
Implemented by adding field to .toml and tested on 4 shards to 
  - index (routed and root docs are on same shard);
  - delete (deleting routed doc once route is found in ID);
  - update (content update is not related with route, in case tested)
  - reject (mapping mismatch rejected doc re-indexed when updated)
cases and it seems working well now!

@hartmut-co-uk , I have deleted (from source) parent concept as custom routing is same on parent-child structure. Thanks for this!

Are there any other cases am I missing?

**Comment by dnault** [comment]
Although we appreciate this pull request, we don't think we're going to integrate it.

The current limitations of the DCP protocol make it impossible to implement a clean and complete solution, and we're thinking the use case for a partial solution is too narrow.

Our current plan is to wait and see if there is a cluster-side solution that would allow us to do this more elegantly in the future. Let us know what you think.

**Comment by mashhur** [comment]
Great and yeah current implementation looks like **work around way** to achieve custom routing. Think there should be other clean way IMHO!
Any way to follow, get notified when status changes (to email: mashhur.sattorov@gmail.com) this [issue](https://issues.couchbase.com/browse/CBES-106)?

Thanks!

**Comment by dnault** [comment]
> Any way to follow, get notified when status changes?

Sure! Request an account on [Couchbase Jira](https://issues.couchbase.com/). Below the login form, there's a "contact Jira Administrators" link that takes you to the request page. Give the admins some time to approve your request (it's currently a manual process).

Once you have an account, visit https://issues.couchbase.com/browse/CBES-106 . On the right side of that page, click "Start watching this issue".

**Comment by brett19** [comment]
Closed as per request from @dnault

**Comment by envitraux** [comment]
I would have loved this feature too. I got around the problem by writing the child documents directly to ElasticSearch using their API client. I know the ElasticSearch people are not keen on Joins either, but it is hard denormalize a relationship where there is one parent for thousands of children. In an interesting note. The ES API has some nice features to do bulk indexing and deletes

**Pull request closed without merging**
